In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import MaxPooling2D

In [14]:

# define input image
image = np.array([[8, 4, 2, 3, 9, 1],
				[0, 6, 4, 3, 7, 10],
				[2, 0, 1, 3, 5, 8],
                [6, 3, 1, 4, 8, 2],
                [0, 2, 4, 3, 5, 9],
				[2, 7, 9, 1, 3, 5]])
image = image.reshape(1, 6, 6, 1)

# define model containing just a single max pooling layer
model = Sequential(
	[MaxPooling2D(pool_size = 2, strides = 2)])

# generate pooled output
output = model.predict(image)

# print output image
output = np.squeeze(output)
print(output)


1/1 [==============================] - 0s 43ms/step
[[ 8  4 10]
 [ 6  4  8]
 [ 7  9  9]]
